Update sparrow.yaml

diff --git a/sparrow.yaml b/sparrow.yaml
--- a/sparrow.yaml
+++ b/sparrow.yaml
@@ -18,15 +18,7 @@ tasks:
         name: stepci_run
         language: Bash
         code: |
-          stepci run $workflow
-          code=$?
-          if [ "$code" -ne "0" ]; then
-            cat << 'HERE' > $cache_root_dir/state.json
-              {
-                "failure" : true 
-              }
-            HERE
-          fi
+          stepci run $workflow || echo '{ "failure" : true  }' > $cache_root_dir/state.json
     depends:
       -
         name: install 
